# Generated by Django 4.0.6 on 2022-07-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveysite', '0003_rename_test_survey_survey_question_survey_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveysite.survey'),
        ),
    ]
