# Generated by Django 4.0.6 on 2022-07-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysite', '0004_alter_response_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='unique_id',
            field=models.IntegerField(null=True),
        ),
    ]
