# Generated by Django 4.0.6 on 2022-07-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysite', '0006_alter_survey_unique_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ('unique_id',)},
        ),
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
